name    'juniper-pyez'
version '0.1.0'
source ''
author 'Rick Sherman, Juniper Networks'
license 'Apache 2.0'
summary ''
description ''
project_page ''

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
